### ISSUE TITLE
油猴脚本版插件不生效

### ISSUE THREAD

**Issue by Staph0214** [xingrz/awsl#10]
Chrome版本 121.0.6167.185（正式版本） （64 位）
油猴版本 V5.0.1
awsl插件 V2.4.0
现象：
![QQ截图20240216213628](https://github.com/xingrz/awsl/assets/45540949/c35b4558-6d4a-492b-8631-5beb66e1f4c2)
描述：用导演的这个插件一直有这个问题，插件有时会生效，有时不生效，不知道为什么，包括之前的版本和2.4.0都有这个问题。
另外，我另一台新电脑就可以用，但是chrome账号都是同步的，安装的插件（包括其他插件）也是一样的。

**Comment by XMoon** [comment]
应该是这个问题 目前没有应用到www.weibo.com 手动连接改成weibo.com 或者导演有空看看加一下匹配

**Comment by xingrz** [comment]
> 应该是这个问题 目前没有应用到www.weibo.com 手动连接改成weibo.com 或者导演有空看看加一下匹配

感谢。更新到 2.5.0 应该好了。
