### ISSUE TITLE
希望可以适配微博Lite

### ISSUE THREAD

**Issue by InsulateJustf** [xingrz/awsl#4]
希望可以适配[微博Lite](https://m.weibo.cn/)，这样就可以有一个PWA的近似Share的微博客户端了

**Comment by xingrz** [comment]
这应该是「微博Lite」而不是这个脚本应该做的事情。

**Comment by InsulateJustf** [comment]
啊我是不是没有表述清楚，微博 Lite 是已经支持了 PWA 的，是希望这个脚本对微博 Lite 适配，这样的话在电脑上就可以拥有近似 Share 的体验了

**Comment by xingrz** [comment]
PWA 支持油猴脚本或者 Chrome 扩展？

**Comment by InsulateJustf** [comment]
> PWA 支持油猴脚本或者 Chrome 扩展？

PC 上的话是的，手机没有
