### ISSUE TITLE
为什么在DEFAULT_WORDS后面加上自定义短语，转发按钮会变成双行

### ISSUE THREAD

**Issue by deathxpuppet** [xingrz/awsl#9]

**Comment by xingrz** [comment]
不奇怪。只要你的短语加得足够多，它甚至能变成三行。

**Comment by deathxpuppet** [comment]
![image](https://user-images.githubusercontent.com/103059160/222886234-09c5bcd4-fcb4-4bb4-9264-7afff3091cbc.png)
不不不，我指的是两行一模一样的

**Comment by deathxpuppet** [comment]
> 不奇怪。只要你的短语加得足够多，它甚至能变成三行。
> 
> <img alt="截屏2023-03-04 01 58 54" width="606" src="https://user-images.githubusercontent.com/288288/222793737-9d7f5d46-7c11-4bfc-92ad-1633a9f853a6.png">

![image](https://user-images.githubusercontent.com/103059160/222899954-301c0a84-4f56-44d4-98fd-ba98eb5eb7bc.png)
不不不，我指的是两行一模一样的
